image: debian/unstable
arch: arm64
packages:
  - build-essential
  - nasm
  - yasm
sources:
  - https://git.sr.ht/~ashn/sunder
tasks:
  - c99-debug-c-backend: |
      cd sunder
      make clean check examples CFLAGS='$(C99_DBG)' SUNDER_DEFAULT_BACKEND=C
  - c99-debug-nasm-backend: |
      cd sunder
      make clean check examples CFLAGS='$(C99_DBG)' SUNDER_DEFAULT_BACKEND=nasm
  - c99-debug-yasm-backend: |
      cd sunder
      make clean check examples CFLAGS='$(C99_DBG)' SUNDER_DEFAULT_BACKEND=yasm
  - c99-release: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)'
triggers:
  - action: email
    condition: failure
    to: "<me@ashn.dev>"
