image: debian/stable
arch: amd64
packages:
  - build-essential
  - gcc-multilib
  - clang
  - nasm
  - yasm
sources:
  - https://git.sr.ht/~ashn/sunder
tasks:
  - c99-debug-yasm: |
      cd sunder
      make clean check examples CFLAGS='$(C99_DBG)' SUNDER_DEFAULT_BACKEND=yasm
  - c99-debug-nasm: |
      cd sunder
      make clean check examples CFLAGS='$(C99_DBG)' SUNDER_DEFAULT_BACKEND=nasm
  - c99-release: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)'
  - clang-debug: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_DBG)'
  - clang-debug-x86-sunder-compile: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_DBG) -m32'
  - clang-release: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_REL)'
  - gcc-debug: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_DBG)'
  - gcc-debug-x86-sunder-compile: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_DBG) -m32'
  - gcc-release: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_REL)'
triggers:
  - action: email
    condition: failure
    to: "<me@ashn.dev>"
