image: debian/stable
packages:
  - build-essential
  - clang
  - nasm
sources:
  - https://git.sr.ht/~ashn/sunder
tasks:
  - c99-debug: |
      cd sunder
      make clean all CFLAGS='$(C99_DBG)'
  - c99-release: |
      cd sunder
      make clean all CFLAGS='$(C99_REL)'
  - clang-debug: |
      cd sunder
      make clean all CC=clang CFLAGS='$(GNU_DBG) $(SANITIZE)'
  - clang-release: |
      cd sunder
      make clean all CC=clang CFLAGS='$(GNU_REL)'
  - gcc-debug: |
      cd sunder
      make clean all CC=gcc CFLAGS='$(GNU_DBG) $(SANITIZE)'
  - gcc-release: |
      cd sunder
      make clean all CC=gcc CFLAGS='$(GNU_REL)'
triggers:
  - action: email
    condition: failure
    to: "<me@ashn.dev>"
