image: debian/stable
arch: amd64
packages:
  - build-essential
  - gcc-multilib
  - clang
  - nasm
  - yasm
sources:
  - https://git.sr.ht/~ashn/sunder
tasks:
  - c99-debug: |
      cd sunder
      make clean check examples CFLAGS='$(C99_DBG)'
  - c99-release: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)'
  - c99-release-c-backend-clang: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)' SUNDER_DEFAULT_BACKEND=C SUNDER_DEFAULT_CC=clang
  - c99-release-c-backend-gcc: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)' SUNDER_DEFAULT_BACKEND=C SUNDER_DEFAULT_CC=gcc
  - c99-release-nasm-backend: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)' SUNDER_DEFAULT_BACKEND=nasm
  - c99-release-yasm-backend: |
      cd sunder
      make clean check examples CFLAGS='$(C99_REL)' SUNDER_DEFAULT_BACKEND=yasm
  - clang-debug: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_DBG)'
  - clang-release: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_REL)'
  - gcc-debug: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_DBG)'
  - gcc-release: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_REL)'
  - clang-release-x86-sunder-compile: |
      cd sunder
      make clean check examples CC=clang CFLAGS='$(GNU_REL) -m32'
  - gcc-release-x86-sunder-compile: |
      cd sunder
      make clean check examples CC=gcc CFLAGS='$(GNU_REL) -m32'
triggers:
  - action: email
    condition: failure
    to: "<me@ashn.dev>"
